AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create S3 Bucket for terraform.tfstate
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Storage'
        Parameters:
          - BucketName
Parameters:
  BucketName:
    Description: 'The name of the bucket to store the data in. This parameter is required.'
    Type: String
    AllowedPattern: '.+'
    ConstraintDescription: 'Bucket name is required and cannot be empty.'
Conditions:
  HasBucket: !Not [!Equals [!Ref BucketName, '']]
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If [HasBucket, !Ref BucketName, !Ref 'AWS::NoValue']
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: LifeCycleRule
            Status: Enabled
