name: 'Check Terraform'
description: 'Check Terraform'
inputs:
  working_directory:
    description: 'working_directory'
    required: true
runs:
  using: "composite"
  steps:
    - name: TFlint
      working-directory: ${{ inputs.working_directory }}
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        tflint --init --config ${{ github.workspace }}/terraform/.tflint.hcl
        tflint --recursive --config ${{ github.workspace }}/terraform/.tflint.hcl --format=checkstyle | \
        reviewdog -f=checkstyle \
                  -name="tflint" \
                  -reporter=github-pr-review \
                  -filter-mode=nofilter \
                  -fail-on-error=false \
                  -level=warning
      shell: bash

    - name: trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        severity: 'HIGH,CRITICAL'
        scan-ref: ${{ inputs.working_directory }}
        output: trivy-scan-result.txt

    - name: Format Trivy Scan Result
      run: |
        if [ -s trivy-scan-result.txt ]; then
          echo -e "## 脆弱性スキャン結果\n<details><summary>詳細</summary>\n\n\`\`\`\n$(cat trivy-scan-result.txt)\n\`\`\`\n</details>" > formatted-trivy-result.md
        else
          echo -e "## 脆弱性スキャン結果\n脆弱性が検知されませんでした。" > formatted-trivy-result.md
        fi
      shell: bash

    - name: Commnet trivy result
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ github.token }}
        path: formatted-trivy-result.md
        recreate: true

    - name: Terraform validate
      working-directory: ${{ inputs.working_directory }}
      run: terraform validate -no-color
      shell: bash

    - name: Terraform fmt
      id: fmt
      working-directory: ${{ inputs.working_directory }}
      run: terraform fmt -check -recursive
      shell: bash
