name: Deploy
on:
  pull_request:
    branches: develop
    types: [closed] # Mergeされたら起動
permissions:
  id-token: write
  contents: read
env:
  WORKING_DIRECTORY: "terraform/aws/iam/dev"
jobs:
  deploy:
    # マージされた時のみ起動
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # GitHubのEnvironments Secretsから各環境に登録してある環境変数を使用
    environment: dev
    steps:
      - name: Checkout infra repository
        uses: actions/checkout@v4
        with:
          ref: develop # developブランチをチェックアウト
      - name: Check Repository
        run: |
          echo "This repository"
          git branch
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0
      - name: Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIRECTORY }}
