name: 'Notify slack'
description: 'Notify slack'
inputs:
  slack_webhook:
    description: 'slack_webhook'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get workflow status
      uses: technote-space/workflow-conclusion-action@v3

    - name: Notify slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_COLOR: ${{ env.WORKFLOW_CONCLUSION }}
        SLACK_TITLE: ${{ env.WORKFLOW_CONCLUSION }}
        SLACK_MESSAGE: "`${{ github.workflow }}` workflow ${{ env.WORKFLOW_CONCLUSION == 'success' && 'success 🚀' || 'failure 😢' }}"
