cloudwatch:
  - terraform/aws/modules/cloudwatch/**
ec2:
  - terraform/aws/modules/ec2/**
iam:
  - terraform/aws/modules/iam/**
identity_center:
  - terraform/aws/modules/identity_center/**
kms:
  - terraform/aws/modules/kms/**
lambda:
  - terraform/aws/modules/lambda/**
network:
  - terraform/aws/modules/network/**
organizations:
  - terraform/aws/modules/organizations/**
s3:
  - terraform/aws/modules/s3/**
sg:
  - terraform/aws/modules/sg/**
sns:
  - terraform/aws/modules/sns/**
ssm:
  - terraform/aws/modules/ssm/**
