name: Apply
on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions:
  contents: read
  id-token: write
  pull-requests: write
env:
  WORKING_DIRECTORY: terraform/aws/environments
jobs:
  detect:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      target_dirs: ${{ steps.detect_changes.outputs.target_dirs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changes
        id: detect_changes
        uses: ./.github/actions/detect_changes

  apply:
    needs: detect
    if: ${{ fromJSON(needs.detect.outputs.target_dirs)[0] != null }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.target_dir }}
    strategy:
      matrix:
        target_dir: ${{ fromJSON(needs.detect.outputs.target_dirs) }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Setup library
        uses: ./.github/actions/setup_library
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}/${{ matrix.target_dir }}
          oidc_role_arn: ${{ secrets.OIDC_ROLE_ARN }}

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIRECTORY }}/${{ matrix.target_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt -var target:${{ matrix.target_dir }} apply -- terraform apply -auto-approve

  notify_slack:
    needs: [detect, apply]
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify slack
        uses: ./.github/actions/notify_slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
