name: Check
on:
  # push:
  #   branches:
  #     - 'main'
  # Only run when Push or make PR
  pull_request:
    branches: main
# Cancel if workflow is running in the same group.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  id-token: write
  pull-requests: write
env:
  WORKING_DIRECTORY: "${{ github.workspace }}/terraform/aws/environments/mng/oidc"
jobs:
  check:
    runs-on: ubuntu-latest
    # Use environment variables registered in Environments Secrets on GitHub
    environment: mng
    steps:
      ##################################################
      # setup
      ##################################################
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check branch
        run: |
          git branch
          echo "Current branch: ${GITHUB_HEAD_REF:-$GITHUB_REF}"
      - name: Get changed dirs
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/path-filter.yml
      - name: Output changed files
        if: steps.filter.outputs.terraform_dev == 'true'
        run: |
          echo "=== Environments ==="
          echo ${{ steps.paths-filter.outputs.modules }}
          echo "=== Modules ==="
          echo ${{ steps.paths-filter.outputs.environments }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
          aqua_opts: ""
        env:
          AQUA_CONFIG: aqua.yaml
          AQUA_DISABLE_COSIGN: true
          AQUA_DISABLE_SLSA: true
      - name: Setup Terraform # ここを消すとfmt/planのコメントがうまくいかない...
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      ##################################################
      # TFLint
      ##################################################
      - name: TFlint
        working-directory: ${{ github.workspace }}/terraform/aws
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tflint --init --config ${{ github.workspace }}/terraform/.tflint.hcl
          tflint --recursive --config ${{ github.workspace }}/terraform/.tflint.hcl --format=checkstyle | \
          reviewdog -f=checkstyle \
                    -name="tflint" \
                    -reporter=github-pr-review \
                    -filter-mode=nofilter \
                    -fail-on-error=false \
                    -level=warning
        continue-on-error: true # Don't stop when an error occurs

      ##################################################
      # tfsec
      ##################################################
      - name: Run tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          working_directory: ${{ github.workspace }}/terraform/aws
          github_token: ${{ secrets.GITHUB_TOKEN }}

      ##################################################
      # fmt
      ##################################################
      - name: Format Terraform
        id: fmt
        run: terraform fmt -check -recursive # Output a list of filenames whose files are not properly formatted.
        continue-on-error: true # Don't stop when an error occurs
      - name: Comment fmt
        uses: actions/github-script@v7
        env:
          FMT: ${{ steps.fmt.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use tokens automatically generated by Github
          script: |
            const output = `
            #### Terraform fmt 🖌\`${{ steps.fmt.outcome }}\`
            <details>
            <summary>Show fmt</summary>
            \n\`\`\`\n${process.env.FMT}\`\`\`
            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      ##################################################
      # plan
      ##################################################
      - name: Init Terraform
        run: terraform init
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Plan Terraform
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}
        continue-on-error: true # Don't stop when an error occurs.
      - name: Comment plan
        uses: actions/github-script@v7
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use tokens automatically generated by Github
          script: |
            const output = `
            #### Terraform plan 📖\`${{ steps.plan.outcome }}\`
            Commit sha ${{ github.sha }} \
            <details>
            <summary>Show plan</summary>
            \n\`\`\`${process.env.PLAN}\`\`\`
            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
