name: Scheduled full check
on:
  schedule:
    - cron: '0 1 * * 1' # Every monday ad AM.10(Asia/Tokyo)
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  id-token: write
  pull-requests: write
env:
  WORKING_DIRECTORY: terraform/aws
jobs:
  full-ci:
    if: ${{ github.ref }} == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for Gitleaks scan.

      - name: Check branch
        run: |
          echo "Current branch: ${{ GITHUB.HEAD_REF }}"

      - name: Setup library
        uses: ./.github/actions/setup_library
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}
          skip_configure_aws: true

      - name: Check Terraform
        uses: ./.github/actions/check
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}

  notify_slack:
    needs: [full-ci]
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify slack
        uses: ./.github/actions/notify_slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
